### PR TITLE
add TypeScript type definition

### PR DESCRIPTION
**Pull request by Xiapeixu**
add TypeScript type definition

### CODE REVIEW

**Comment by Xiapeixu** [comment]
@mikeymckay https://github.com/Mobius1/Selectr/wiki/Options#allowdeselect Errors in Wiki

**Comment by Xiapeixu** [comment]
@mikeymckay https://github.com/Mobius1/Selectr/wiki/Options#allowdeselect 
Errors in Wiki,The type of allowdeselect should be Boolean

**Comment by Xiapeixu** [comment]
@mikeymckay https://github.com/Mobius1/Selectr/wiki/Options#messages
messages Missing parameters. searchPlaceholder and noOptions

**Comment by Xiapeixu** [comment]
@Mobius1 Can you release a new version

**Comment by Mobius1** [comment]
Done

**Pull request merged**
