### PR TITLE
Adds nativeKeyboard Module

### PR DESCRIPTION
**Pull request by adrian-enspired**
Adds optional native-like keyboard behaviors to Selectr.  This behavior is disabled by default; pass `nativeKeyboard: true` in the constructor options to enable it.
```js
new Selectr( mySelectElement, { nativeKeyboard: true } );
```

- When focused, <kbd>Enter</kbd>, <kbd>   </kbd>, <kbd>↓</kbd>, and <kbd>↑</kbd> will toggle the selectr open
- When focused, <kbd>Esc</kbd> and <kbd>   </kbd> will toggle the selectr closed
- When focused, typing (printable characters) will search display text (from start of string) and select the first matching option on a select-one
- When focused, typing (printable characters) will trigger the `search()` feature on a select-multi

Also:

- Adds QUnit tests for new functionality
  tests run+pass on Chrome and FireFox on Linux; other browsers not yet tested
- Adds `util.startsWith()` for start-of-string matching
- Adds `anchor` argument to `search()`; pass `true` for start-of-string matching
- `search()` no longer ignores one-character search strings

### CODE REVIEW

**Comment by adrian-enspired** [comment]
Apparently Travis doesn't understand `new KeyboardEvent`  :disappointed: 
I will make a more "failsafe" version of `doKeypress` for tests.

**Comment by adrian-enspired** [comment]
OK; I'm not sure how to get these tests going in Travis (in phantomJS).  The issue is that phantom doesn't seem to understand/properly implement keyboard events:
```
>> Message: Died on test #1 file:///home/travis/build/Mobius1/Selectr/tests/index.js:235:19
>> file:///home/travis/build/Mobius1/Selectr/tests/index.js:347:7
>> global code@file:///home/travis/build/Mobius1/Selectr/tests/index.js:348:3: KeyboardEventConstructor is not a constructor (evaluating 'new KeyboardEvent( type, { key: character } )')
```
Trying to trigger these events in other ways (`initKeyboardEvent`, etc.) is not working well with "real" browsers.  I know phantom has a `sendEvent` method, but that's phantom's api, not inside the phantom browser.

if anyone has suggestions I'd be happy to hear them.

**Comment by adrian-enspired** [comment]
hacked it up; Travis passes.  :smile:

**Comment by Mobius1** [comment]
All done, thanks 👍

**Comment by adrian-enspired** [comment]
wanted to update the wiki but can't seem to figure out how to PR to it: 
https://gist.github.com/adrian-enspired/76b5a5bbf3c64cde0dc8db293962c521

**Comment by Mobius1** [comment]
I've updated the wiki with your gist and credited you: https://github.com/Mobius1/Selectr/wiki/Public-Methods#searchquery-anchor

**Pull request merged**
